/*
 * @(#)ResultSet.java	1.61 06/08/29
 *
 * Copyright 2006 Sun Microsystems, Inc. All rights reserved.
 * SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
 */

package java.sql;

import java.io.InputStream;
import java.io.Reader;
import java.math.BigDecimal;
import java.net.URL;
import java.util.Calendar;
import java.util.Map;

import org.inria.jdbc.Statement;

/**
 * A table of data representing a database result set, which
 * is usually generated by executing a statement that queries the database.
 *
 * <P>A <code>ResultSet</code> object  maintains a cursor pointing
 * to its current row of data.  Initially the cursor is positioned
 * before the first row. The <code>next</code> method moves the
 * cursor to the next row, and because it returns <code>false</code>
 * when there are no more rows in the <code>ResultSet</code> object,
 * it can be used in a <code>while</code> loop to iterate through
 * the result set.
 * <P>
 * A default <code>ResultSet</code> object is not updatable and
 * has a cursor that moves forward only.  Thus, you can
 * iterate through it only once and only from the first row to the
 * last row. It is possible to
 * produce <code>ResultSet</code> objects that are scrollable and/or
 * updatable.  The following code fragment, in which <code>con</code>
 * is a valid <code>Connection</code> object, illustrates how to make
 * a result set that is scrollable and insensitive to updates by others, and
 * that is updatable. See <code>ResultSet</code> fields for other
 * options.
 * <PRE>
 *
 *       Statement stmt = con.createStatement(
 *                                      ResultSet.TYPE_SCROLL_INSENSITIVE,
 *                                      ResultSet.CONCUR_UPDATABLE);
 *       ResultSet rs = stmt.executeQuery("SELECT a, b FROM TABLE2");
 *       // rs will be scrollable, will not show changes made by others,
 *       // and will be updatable
 *
 * </PRE>
 * The <code>ResultSet</code> interface provides
 * <i>getter</i> methods (<code>getBoolean</code>, <code>getLong</code>, and so on)
 * for retrieving column values from the current row.
 * Values can be retrieved using either the index number of the
 * column or the name of the column.  In general, using the
 * column index will be more efficient.  Columns are numbered from 1.
 * For maximum portability, result set columns within each row should be
 * read in left-to-right order, and each column should be read only once.
 *
 * <P>For the getter methods, a JDBC driver attempts
 * to convert the underlying data to the Java type specified in the
 * getter method and returns a suitable Java value.  The JDBC specification
 * has a table showing the allowable mappings from SQL types to Java types
 * that can be used by the <code>ResultSet</code> getter methods.
 * <P>
 * <P>Column names used as input to getter methods are case
 * insensitive.  When a getter method is called  with
 * a column name and several columns have the same name,
 * the value of the first matching column will be returned.
 * The column name option is
 * designed to be used when column names are used in the SQL
 * query that generated the result set.
 * For columns that are NOT explicitly named in the query, it
 * is best to use column numbers. If column names are used, the
 * programmer should take care to guarantee that they uniquely refer to
 * the intended columns, which can be assured with the SQL <i>AS</i> clause.
 * <P>
 * A set of updater methods were added to this interface
 * in the JDBC 2.0 API (Java<sup><font size=-2>TM</font></sup> 2 SDK,
 * Standard Edition, version 1.2). The comments regarding parameters
 * to the getter methods also apply to parameters to the
 * updater methods.
 *<P>
 * The updater methods may be used in two ways:
 * <ol>
 * <LI>to update a column value in the current row.  In a scrollable
 *     <code>ResultSet</code> object, the cursor can be moved backwards
 *     and forwards, to an absolute position, or to a position
 *     relative to the current row.
 *     The following code fragment updates the <code>NAME</code> column
 *     in the fifth row of the <code>ResultSet</code> object
 *     <code>rs</code> and then uses the method <code>updateRow</code>
 *     to update the data source table from which <code>rs</code> was derived.
 * <PRE>
 *
 *       rs.absolute(5); // moves the cursor to the fifth row of rs
 *       rs.updateString("NAME", "AINSWORTH"); // updates the
 *          // <code>NAME</code> column of row 5 to be <code>AINSWORTH</code>
 *       rs.updateRow(); // updates the row in the data source
 *
 * </PRE>
 * <LI>to insert column values into the insert row.  An updatable
 *     <code>ResultSet</code> object has a special row associated with
 *     it that serves as a staging area for building a row to be inserted.
 *     The following code fragment moves the cursor to the insert row, builds
 *     a three-column row, and inserts it into <code>rs</code> and into
 *     the data source table using the method <code>insertRow</code>.
 * <PRE>
 *
 *       rs.moveToInsertRow(); // moves cursor to the insert row
 *       rs.updateString(1, "AINSWORTH"); // updates the
 *          // first column of the insert row to be <code>AINSWORTH</code>
 *       rs.updateInt(2,35); // updates the second column to be <code>35</code>
 *       rs.updateBoolean(3, true); // updates the third column to <code>true</code>
 *       rs.insertRow();
 *       rs.moveToCurrentRow();
 *
 * </PRE>
 * </ol>
 * <P>A <code>ResultSet</code> object is automatically closed when the
 * <code>Statement</code> object that
 * generated it is closed, re-executed, or used
 * to retrieve the next result from a sequence of multiple results.
 *
 * <P>The number, types and properties of a <code>ResultSet</code>
 * object's columns are provided by the <code>ResulSetMetaData</code>
 * object returned by the <code>ResultSet.getMetaData</code> method.
 *
 * @see Statement#executeQuery
 * @see Statement#getResultSet
 * @see ResultSetMetaData
 */

public interface ResultSet {

  /**
   * Moves the cursor froward one row from its current position.
   * A <code>ResultSet</code> cursor is initially positioned
   * before the first row; the first call to the method
   * <code>next</code> makes the first row the current row; the
   * second call makes the second row the current row, and so on.
   * <p>
   * When a call to the <code>next</code> method returns <code>false</code>,
   * the cursor is positioned after the last row. Any
   * invocation of a <code>ResultSet</code> method which requires a
   * current row will result in a <code>SQLException</code> being thrown.
   *  If the result set type is <code>TYPE_FORWARD_ONLY</code>, it is vendor specified
   * whether their JDBC driver implementation will return <code>false</code> or
   *  throw an <code>SQLException</code> on a
   * subsequent call to <code>next</code>.
   *
   * <P>If an input stream is open for the current row, a call
   * to the method <code>next</code> will
   * implicitly close it. A <code>ResultSet</code> object's
   * warning chain is cleared when a new row is read.
   *
   * @return <code>true</code> if the new current row is valid;
   * <code>false</code> if there are no more rows
   * @exception SQLException if a database access error occurs or this method is
   *            called on a closed result set
   */
  boolean next() throws SQLException;


  /**
   * Releases this <code>ResultSet</code> object's database and
   * JDBC resources immediately instead of waiting for
   * this to happen when it is automatically closed.
   *
   * <P>The closing of a <code>ResultSet</code> object does <strong>not</strong> close the <code>Blob</code>,
   * <code>Clob</code> or <code>NClob</code> objects created by the <code>ResultSet</code>. <code>Blob</code>,
   * <code>Clob</code> or <code>NClob</code> objects remain valid for at least the duration of the
   * transaction in which they are creataed, unless their <code>free</code> method is invoked.
   *<p>
   * When a <code>ResultSet</code> is closed, any <code>ResultSetMetaData</code>
   * instances that were created by calling the  <code>getMetaData</code>
   * method remain accessible.
   *
   * <P><B>Note:</B> A <code>ResultSet</code> object
   * is automatically closed by the
   * <code>Statement</code> object that generated it when
   * that <code>Statement</code> object is closed,
   * re-executed, or is used to retrieve the next result from a
   * sequence of multiple results.
   *<p>
   * Calling the method <code>close</code> on a <code>ResultSet</code>
   * object that is already closed is a no-op.
   * <P>
   * <p>
   *
   * @exception SQLException if a database access error occurs
   */
  void close() throws SQLException;

  /**
   * Reports whether
   * the last column read had a value of SQL <code>NULL</code>.
   * Note that you must first call one of the getter methods
   * on a column to try to read its value and then call
   * the method <code>wasNull</code> to see if the value read was
   * SQL <code>NULL</code>.
   *
   * @return <code>true</code> if the last column value read was SQL
   *         <code>NULL</code> and <code>false</code> otherwise
   * @exception SQLException if a database access error occurs or this method is
   *            called on a closed result set
   */
  boolean wasNull() throws SQLException;

  // Methods for accessing results by column index

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>String</code> in the Java programming language.
   *
   * @param columnIndex the first column is 1, the second is 2, ...
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnIndex is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  String getString(int columnIndex) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * an <code>int</code> in the Java programming language.
   *
   * @param columnIndex the first column is 1, the second is 2, ...
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>0</code>
   * @exception SQLException if the columnIndex is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  int getInt(int columnIndex) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>byte</code> array in the Java programming language.
   * The bytes represent the raw values returned by the driver.
   *
   * @param columnIndex the first column is 1, the second is 2, ...
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnIndex is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  byte[] getBytes(int columnIndex) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>java.sql.Date</code> object in the Java programming language.
   *
   * @param columnIndex the first column is 1, the second is 2, ...
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnIndex is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  java.sql.Date getDate(int columnIndex) throws SQLException;


  // Methods for accessing results by column label

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>String</code> in the Java programming language.
   *
   * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnLabel is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  String getString(String columnLabel) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * an <code>int</code> in the Java programming language.
   *
   * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>0</code>
   * @exception SQLException if the columnLabel is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  int getInt(String columnLabel) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>byte</code> array in the Java programming language.
   * The bytes represent the raw values returned by the driver.
   *
   * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnLabel is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  byte[] getBytes(String columnLabel) throws SQLException;

  /**
   * Retrieves the value of the designated column in the current row
   * of this <code>ResultSet</code> object as
   * a <code>java.sql.Date</code> object in the Java programming language.
   *
   * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
   * @return the column value; if the value is SQL <code>NULL</code>, the
   * value returned is <code>null</code>
   * @exception SQLException if the columnLabel is not valid;
   * if a database access error occurs or this method is
   *            called on a closed result set
   */
  java.sql.Date getDate(String columnLabel) throws SQLException;


  /**
   * Retrieves the  number, types and properties of
   * this <code>ResultSet</code> object's columns.
   *
   * @return the description of this <code>ResultSet</code> object's columns
   * @exception SQLException if a database access error occurs or this method is
   *            called on a closed result set
   */
  ResultSetMetaData getMetaData() throws SQLException;


  //----------------------------------------------------------------

  /**
   * Maps the given <code>ResultSet</code> column label to its
   * <code>ResultSet</code> column index.
   *
   * @param columnLabel the label for the column specified with the SQL AS clause.  If the SQL AS clause was not specified, then the label is the name of the column
   * @return the column index of the given column name
   * @exception SQLException if the <code>ResultSet</code> object
   * does not contain a column labeled <code>columnLabel</code>, a database access error occurs
   *  or this method is called on a closed result set
   */
  int findColumn(String columnLabel) throws SQLException;

  /**
   * Moves the cursor a relative number of rows, either positive or negative.
   * Attempting to move beyond the first/last row in the
   * result set positions the cursor before/after the
   * the first/last row. Calling <code>relative(0)</code> is valid, but does
   * not change the cursor position.
   *
   * <p>Note: Calling the method <code>relative(1)</code>
   * is identical to calling the method <code>next()</code> and
   * calling the method <code>relative(-1)</code> is identical
   * to calling the method <code>previous()</code>.
   *
   * @param rows an <code>int</code> specifying the number of rows to
   *        move from the current row; a positive number moves the cursor
   *        forward; a negative number moves the cursor backward
   * @return <code>true</code> if the cursor is on a row;
   *         <code>false</code> otherwise
   * @exception SQLException if a database access error occurs;  this method
   * is called on a closed result set or the result set type is
   *            <code>TYPE_FORWARD_ONLY</code>
   * @exception SQLFeatureNotSupportedException if the JDBC driver does not support
   * this method
   * @since 1.2
   */
  boolean relative(int rows) throws SQLException; /**/

  Blob getBlob( int columnIndex ) throws SQLException;
  Blob getBlob( String columnLabel ) throws SQLException;


<T> T unwrap(Class<T> iface) throws SQLException;


boolean isWrapperFor(Class<?> iface) throws SQLException;


boolean absolute(int row) throws SQLException;


void afterLast() throws SQLException;


void beforeFirst() throws SQLException;


void cancelRowUpdates() throws SQLException;


void clearWarnings() throws SQLException;


void deleteRow() throws SQLException;


boolean first() throws SQLException;


Array getArray(int columnIndex) throws SQLException;


Array getArray(String colName) throws SQLException;


InputStream getAsciiStream(int columnIndex) throws SQLException;


InputStream getAsciiStream(String columnName) throws SQLException;


BigDecimal getBigDecimal(int columnIndex) throws SQLException;


BigDecimal getBigDecimal(int columnIndex, int scale) throws SQLException;


BigDecimal getBigDecimal(String columnName) throws SQLException;


BigDecimal getBigDecimal(String columnName, int scale) throws SQLException;


InputStream getBinaryStream(int columnIndex) throws SQLException;


InputStream getBinaryStream(String columnName) throws SQLException;


boolean getBoolean(int columnIndex) throws SQLException;


boolean getBoolean(String columnName) throws SQLException;


byte getByte(int columnIndex) throws SQLException;


byte getByte(String columnName) throws SQLException;


Reader getCharacterStream(int columnIndex) throws SQLException;


Reader getCharacterStream(String columnName) throws SQLException;


Clob getClob(int columnIndex) throws SQLException;


Clob getClob(String colName) throws SQLException;


int getConcurrency() throws SQLException;


String getCursorName() throws SQLException;


Date getDate(int columnIndex, Calendar cal) throws SQLException;


Date getDate(String columnName, Calendar cal) throws SQLException;


double getDouble(int columnIndex) throws SQLException;


double getDouble(String columnName) throws SQLException;


int getFetchDirection() throws SQLException;


int getFetchSize() throws SQLException;


float getFloat(int columnIndex) throws SQLException;


float getFloat(String columnName) throws SQLException;


long getLong(int columnIndex) throws SQLException;


long getLong(String columnName) throws SQLException;


Object getObject(int columnIndex) throws SQLException;


Object getObject(int columnIndex, Map<String, Class<?>> map)
		throws SQLException;


Object getObject(String columnName) throws SQLException;


Object getObject(String columnName, Map<String, Class<?>> map)
		throws SQLException;


Ref getRef(int columnIndex) throws SQLException;


Ref getRef(String colName) throws SQLException;


int getRow() throws SQLException;


short getShort(int columnIndex) throws SQLException;


short getShort(String columnName) throws SQLException;


java.sql.Statement getStatement() throws SQLException;


Time getTime(int columnIndex) throws SQLException;


Time getTime(int columnIndex, Calendar cal) throws SQLException;


Time getTime(String columnName) throws SQLException;


Time getTime(String columnName, Calendar cal) throws SQLException;


Timestamp getTimestamp(int columnIndex) throws SQLException;


Timestamp getTimestamp(int columnIndex, Calendar cal) throws SQLException;


Timestamp getTimestamp(String columnName) throws SQLException;


Timestamp getTimestamp(String columnName, Calendar cal) throws SQLException;


int getType() throws SQLException;


InputStream getUnicodeStream(int columnIndex) throws SQLException;


InputStream getUnicodeStream(String columnName) throws SQLException;


URL getURL(int columnIndex) throws SQLException;


URL getURL(String columnName) throws SQLException;


SQLWarning getWarnings() throws SQLException;


void insertRow() throws SQLException;


boolean isAfterLast() throws SQLException;


boolean isBeforeFirst() throws SQLException;


boolean isFirst() throws SQLException;


boolean isLast() throws SQLException;


boolean last() throws SQLException;


void moveToCurrentRow() throws SQLException;


void moveToInsertRow() throws SQLException;


boolean previous() throws SQLException;


void refreshRow() throws SQLException;


boolean rowDeleted() throws SQLException;


boolean rowInserted() throws SQLException;


boolean rowUpdated() throws SQLException;


void setFetchDirection(int direction) throws SQLException;


void setFetchSize(int rows) throws SQLException;


void updateArray(int columnIndex, Array x) throws SQLException;


void updateArray(String columnName, Array x) throws SQLException;


void updateAsciiStream(int columnIndex, InputStream x, int length)
		throws SQLException;


void updateAsciiStream(String columnName, InputStream x, int length)
		throws SQLException;


void updateBigDecimal(int columnIndex, BigDecimal x) throws SQLException;


void updateBigDecimal(String columnName, BigDecimal x) throws SQLException;


void updateBinaryStream(int columnIndex, InputStream x, int length)
		throws SQLException;


void updateBinaryStream(String columnName, InputStream x, int length)
		throws SQLException;


void updateBlob(int columnIndex, Blob x) throws SQLException;


void updateBlob(String columnName, Blob x) throws SQLException;


void updateBoolean(int columnIndex, boolean x) throws SQLException;


void updateBoolean(String columnName, boolean x) throws SQLException;


void updateByte(int columnIndex, byte x) throws SQLException;


void updateByte(String columnName, byte x) throws SQLException;


void updateBytes(int columnIndex, byte[] x) throws SQLException;


void updateBytes(String columnName, byte[] x) throws SQLException;


void updateCharacterStream(int columnIndex, Reader x, int length)
		throws SQLException;


void updateCharacterStream(String columnName, Reader reader, int length)
		throws SQLException;


void updateClob(int columnIndex, Clob x) throws SQLException;


void updateClob(String columnName, Clob x) throws SQLException;


void updateDate(int columnIndex, Date x) throws SQLException;


void updateDate(String columnName, Date x) throws SQLException;


void updateDouble(int columnIndex, double x) throws SQLException;


void updateDouble(String columnName, double x) throws SQLException;


void updateFloat(int columnIndex, float x) throws SQLException;


void updateFloat(String columnName, float x) throws SQLException;


void updateInt(int columnIndex, int x) throws SQLException;


void updateInt(String columnName, int x) throws SQLException;


void updateLong(int columnIndex, long x) throws SQLException;


void updateLong(String columnName, long x) throws SQLException;


void updateNull(int columnIndex) throws SQLException;


void updateNull(String columnName) throws SQLException;


void updateObject(int columnIndex, Object x) throws SQLException;


void updateObject(int columnIndex, Object x, int scale) throws SQLException;


void updateObject(String columnName, Object x) throws SQLException;


void updateObject(String columnName, Object x, int scale) throws SQLException;


void updateRef(int columnIndex, Ref x) throws SQLException;


void updateRef(String columnName, Ref x) throws SQLException;


void updateRow() throws SQLException;


void updateShort(int columnIndex, short x) throws SQLException;


void updateShort(String columnName, short x) throws SQLException;


void updateString(int columnIndex, String x) throws SQLException;


void updateString(String columnName, String x) throws SQLException;


void updateTime(int columnIndex, Time x) throws SQLException;


void updateTime(String columnName, Time x) throws SQLException;


void updateTimestamp(int columnIndex, Timestamp x) throws SQLException;


void updateTimestamp(String columnName, Timestamp x) throws SQLException;


RowId getRowId(int columnIndex) throws SQLException;


RowId getRowId(String columnLabel) throws SQLException;


void updateRowId(int columnIndex, RowId value) throws SQLException;


void updateRowId(String columnLabel, RowId value) throws SQLException;


int getHoldability() throws SQLException;


boolean isClosed() throws SQLException;


void updateNString(int columnIndex, String nString) throws SQLException;


void updateNString(String columnLabel, String nString) throws SQLException;


void updateNClob(int columnIndex, NClob nClob) throws SQLException;


void updateNClob(String columnLabel, NClob nClob) throws SQLException;


NClob getNClob(int columnIndex) throws SQLException;


NClob getNClob(String columnLabel) throws SQLException;


SQLXML getSQLXML(int columnIndex) throws SQLException;


SQLXML getSQLXML(String columnLabel) throws SQLException;


void updateSQLXML(int columnIndex, SQLXML xmlObject) throws SQLException;


void updateSQLXML(String columnLabel, SQLXML xmlObject) throws SQLException;


String getNString(int columnIndex) throws SQLException;


String getNString(String columnLabel) throws SQLException;


Reader getNCharacterStream(int columnIndex) throws SQLException;


Reader getNCharacterStream(String columnLabel) throws SQLException;


void updateNCharacterStream(int columnIndex, Reader x, long length)
		throws SQLException;


void updateNCharacterStream(String columnLabel, Reader reader, long length)
		throws SQLException;


void updateAsciiStream(int columnIndex, InputStream x, long length)
		throws SQLException;


void updateBinaryStream(int columnIndex, InputStream x, long length)
		throws SQLException;


void updateCharacterStream(int columnIndex, Reader x, long length)
		throws SQLException;


void updateAsciiStream(String columnLabel, InputStream x, long length)
		throws SQLException;


void updateBinaryStream(String columnLabel, InputStream x, long length)
		throws SQLException;


void updateCharacterStream(String columnLabel, Reader reader, long length)
		throws SQLException;


void updateBlob(int columnIndex, InputStream inputStream, long length)
		throws SQLException;


void updateBlob(String columnLabel, InputStream inputStream, long length)
		throws SQLException;


void updateClob(int columnIndex, Reader reader, long length)
		throws SQLException;


void updateClob(String columnLabel, Reader reader, long length)
		throws SQLException;


void updateNClob(int columnIndex, Reader reader, long length)
		throws SQLException;


void updateNClob(String columnLabel, Reader reader, long length)
		throws SQLException;


void updateNCharacterStream(int columnIndex, Reader x) throws SQLException;


void updateNCharacterStream(String columnLabel, Reader reader)
		throws SQLException;


void updateAsciiStream(int columnIndex, InputStream x) throws SQLException;


void updateBinaryStream(int columnIndex, InputStream x) throws SQLException;


void updateCharacterStream(int columnIndex, Reader x) throws SQLException;


void updateAsciiStream(String columnLabel, InputStream x) throws SQLException;


void updateBinaryStream(String columnLabel, InputStream x) throws SQLException;


void updateCharacterStream(String columnLabel, Reader reader)
		throws SQLException;


void updateBlob(int columnIndex, InputStream inputStream) throws SQLException;


void updateBlob(String columnLabel, InputStream inputStream)
		throws SQLException;


void updateClob(int columnIndex, Reader reader) throws SQLException;


void updateClob(String columnLabel, Reader reader) throws SQLException;


void updateNClob(int columnIndex, Reader reader) throws SQLException;


void updateNClob(String columnLabel, Reader reader) throws SQLException;
}
